delete from sys_user_scr_options where scr_id in (
select scr_id from sys_screens where scr_name in ('EMPLOYEES','HR_EMP_TYPES','EMPLOYEE_ALLOWANCES','EMPLOYEE_DEDUCTION_TYPES','HR_SHIFT_DEFINITIONS',
'JOB_DESCRIPTION','LEAVE_TYPES','LEAVE_TYPES_GROUPS','ATTENDANCE','ATTENDANCE_UPLOAD','PAYROLL_OPEN','MONTH_PROCESS','MONTH_UNPROCESS','SANDWICH_PROCESS',
'PAYROLL_PROCESS','PAYROLL_TRANSFER','PAYROLL_UNPROCESS','SHIFT_ASSIGNMENTS','SHIFT_CHANGES','CHANGE_REST','DEDUCTIONS','INCENTIVES','INCREMENTS','LOANS',
'HR_GENERATE_OVERTIME','OVERTIME_REQUEST','OVERTIME_PROCESS','OVERTIME_UNPROCESS','EMPLOYEE_WISE_ATTENDANCE','LEAVE_REQUEST','LEAVE_APPROVAL','GAZETTED_HOLIDAY',
'LEAVES_CARRYFORWARD','EMPLOYEE_JOIN_RESIGN','EMPLOYEE_REINSTATE','ADVANCE_SALARY','EMPLOYEE_STRENGTHS','EMPLOYEE_DETAIL','EMPLOYEES_SUMMARY','DEDUCTION_REGISTER',
'TAX_DEDUCTION','EMPLOYEE_ATTENDANCE_SHEET','DEPARTMENT_WISE_ATTENDANCE','EMPLOYEE_WISE_ATTENDANCE','ATTENDANCE_REGISTER_MONTH_WISE','DEPARTMENT_WISE_DAILY_ATTENDAN',
'ATTENDANCE_SUMMARY','ATTENDANCE_SUMMARY_SHIFT','EMPLOYEE_DAILY_ABSENT','EMPLOYEE_DAILY_LATE_COMERS','EMPLOYEE_JOINING_LEAVING','EMPLOYEE_SALARY_BREAKUPS',
'EMPLOYEE_WITHOUT_SALARY_BREAKU','EMPLOYEE_PAYMENT_SHEET','EMPLOYEE_ADVANCE_PAYMENT_SHEET','EMPLOYEE_SALARY_REGISTER','EMPLOYEE_SALARY_SLIP','EMPLOYEE_SALARY_SUMMARY',
'EMPLOYEE_SALARY_DEPT_WISE','EOBI_LEDGER','SS_LEDGER','DEPT_WISE_OT_PAYMENT_SHEET','EMPLOYEE_OVERTIME_TRACKING','OVERTIME_MONTH_SUMMARY','DPARTMENT_WISE_OVER_TMIE_DETAI',
'EMPLOYEE_CARD_PRINTING','EMPLOYEE_BANK_LETTER','BLOOD_GROUP','EMPLOYEE_STRENGTH','EMPLOYEE_REINSTATE_SUMMARY','M_HRPAYROLL','T_HRPAYROLL','R_HRPAYROLL','ATTENDANCE','Attendance'));

delete from sys_scr_options where scr_id in (
select scr_id from sys_screens where scr_name in ('EMPLOYEES','HR_EMP_TYPES','EMPLOYEE_ALLOWANCES','EMPLOYEE_DEDUCTION_TYPES','HR_SHIFT_DEFINITIONS',
'JOB_DESCRIPTION','LEAVE_TYPES','LEAVE_TYPES_GROUPS','ATTENDANCE','ATTENDANCE_UPLOAD','PAYROLL_OPEN','MONTH_PROCESS','MONTH_UNPROCESS','SANDWICH_PROCESS',
'PAYROLL_PROCESS','PAYROLL_TRANSFER','PAYROLL_UNPROCESS','SHIFT_ASSIGNMENTS','SHIFT_CHANGES','CHANGE_REST','DEDUCTIONS','INCENTIVES','INCREMENTS','LOANS',
'HR_GENERATE_OVERTIME','OVERTIME_REQUEST','OVERTIME_PROCESS','OVERTIME_UNPROCESS','EMPLOYEE_WISE_ATTENDANCE','LEAVE_REQUEST','LEAVE_APPROVAL','GAZETTED_HOLIDAY',
'LEAVES_CARRYFORWARD','EMPLOYEE_JOIN_RESIGN','EMPLOYEE_REINSTATE','ADVANCE_SALARY','EMPLOYEE_STRENGTHS','EMPLOYEE_DETAIL','EMPLOYEES_SUMMARY','DEDUCTION_REGISTER',
'TAX_DEDUCTION','EMPLOYEE_ATTENDANCE_SHEET','DEPARTMENT_WISE_ATTENDANCE','EMPLOYEE_WISE_ATTENDANCE','ATTENDANCE_REGISTER_MONTH_WISE','DEPARTMENT_WISE_DAILY_ATTENDAN',
'ATTENDANCE_SUMMARY','ATTENDANCE_SUMMARY_SHIFT','EMPLOYEE_DAILY_ABSENT','EMPLOYEE_DAILY_LATE_COMERS','EMPLOYEE_JOINING_LEAVING','EMPLOYEE_SALARY_BREAKUPS',
'EMPLOYEE_WITHOUT_SALARY_BREAKU','EMPLOYEE_PAYMENT_SHEET','EMPLOYEE_ADVANCE_PAYMENT_SHEET','EMPLOYEE_SALARY_REGISTER','EMPLOYEE_SALARY_SLIP','EMPLOYEE_SALARY_SUMMARY',
'EMPLOYEE_SALARY_DEPT_WISE','EOBI_LEDGER','SS_LEDGER','DEPT_WISE_OT_PAYMENT_SHEET','EMPLOYEE_OVERTIME_TRACKING','OVERTIME_MONTH_SUMMARY','DPARTMENT_WISE_OVER_TMIE_DETAI',
'EMPLOYEE_CARD_PRINTING','EMPLOYEE_BANK_LETTER','BLOOD_GROUP','EMPLOYEE_STRENGTH','EMPLOYEE_REINSTATE_SUMMARY','M_HRPAYROLL','T_HRPAYROLL','R_HRPAYROLL','ATTENDANCE','Attendance'));

delete from sys_screens 
where scr_name in ('EMPLOYEES','HR_EMP_TYPES','EMPLOYEE_ALLOWANCES','EMPLOYEE_DEDUCTION_TYPES','HR_SHIFT_DEFINITIONS',
'JOB_DESCRIPTION','LEAVE_TYPES','LEAVE_TYPES_GROUPS','ATTENDANCE','ATTENDANCE_UPLOAD','PAYROLL_OPEN','MONTH_PROCESS','MONTH_UNPROCESS','SANDWICH_PROCESS',
'PAYROLL_PROCESS','PAYROLL_TRANSFER','PAYROLL_UNPROCESS','SHIFT_ASSIGNMENTS','SHIFT_CHANGES','CHANGE_REST','DEDUCTIONS','INCENTIVES','INCREMENTS','LOANS',
'HR_GENERATE_OVERTIME','OVERTIME_REQUEST','OVERTIME_PROCESS','OVERTIME_UNPROCESS','EMPLOYEE_WISE_ATTENDANCE','LEAVE_REQUEST','LEAVE_APPROVAL','GAZETTED_HOLIDAY',
'LEAVES_CARRYFORWARD','EMPLOYEE_JOIN_RESIGN','EMPLOYEE_REINSTATE','ADVANCE_SALARY','EMPLOYEE_STRENGTHS','EMPLOYEE_DETAIL','EMPLOYEES_SUMMARY','DEDUCTION_REGISTER',
'TAX_DEDUCTION','EMPLOYEE_ATTENDANCE_SHEET','DEPARTMENT_WISE_ATTENDANCE','EMPLOYEE_WISE_ATTENDANCE','ATTENDANCE_REGISTER_MONTH_WISE','DEPARTMENT_WISE_DAILY_ATTENDAN',
'ATTENDANCE_SUMMARY','ATTENDANCE_SUMMARY_SHIFT','EMPLOYEE_DAILY_ABSENT','EMPLOYEE_DAILY_LATE_COMERS','EMPLOYEE_JOINING_LEAVING','EMPLOYEE_SALARY_BREAKUPS',
'EMPLOYEE_WITHOUT_SALARY_BREAKU','EMPLOYEE_PAYMENT_SHEET','EMPLOYEE_ADVANCE_PAYMENT_SHEET','EMPLOYEE_SALARY_REGISTER','EMPLOYEE_SALARY_SLIP','EMPLOYEE_SALARY_SUMMARY',
'EMPLOYEE_SALARY_DEPT_WISE','EOBI_LEDGER','SS_LEDGER','DEPT_WISE_OT_PAYMENT_SHEET','EMPLOYEE_OVERTIME_TRACKING','OVERTIME_MONTH_SUMMARY','DPARTMENT_WISE_OVER_TMIE_DETAI',
'EMPLOYEE_CARD_PRINTING','EMPLOYEE_BANK_LETTER','BLOOD_GROUP','EMPLOYEE_STRENGTH','EMPLOYEE_REINSTATE_SUMMARY','M_HRPAYROLL','T_HRPAYROLL','R_HRPAYROLL','ATTENDANCE','Attendance');