 DECLARE
 A VARCHAR2(20);
 EMP NUMBER;
 CURSOR C1 IS (SELECT EMP_ID,RESTDAY1 FROM HR_EMPLOYEES WHERE RESTDAY1 IS NOT NULL);
 BEGIN
 FOR I IN C1
 LOOP
    FOR J IN (SELECT NEXT_DAY(ATTENDANCE_DATE,I.RESTDAY1) ATTENDANCE_DATE 
              FROM HR_ATTENDANCES 
              WHERE ATTENDANCE_DATE >= TO_DATE('10/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
              AND EMP_ID=I.EMP_ID)
    LOOP
    UPDATE hr_Attendances
    SET ATTENDANCE_STATUS='R'
    WHERE ATTENDANCE_DATE=J.ATTENDANCE_DATE
    AND EMP_ID=I.EMP_ID;
    END LOOP;
    
     END LOOP;
     COMMIT;
 END;
   